// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mahalanobis_depth_cpp
Rcpp::NumericVector mahalanobis_depth_cpp(Rcpp::NumericMatrix x, Rcpp::NumericMatrix data, Rcpp::Nullable<Rcpp::NumericVector> mu, Rcpp::Nullable<Rcpp::NumericMatrix> sigma);
RcppExport SEXP _depthR_mahalanobis_depth_cpp(SEXP xSEXP, SEXP dataSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mahalanobis_depth_cpp(x, data, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// depth_outlyingness
Rcpp::NumericVector depth_outlyingness(Rcpp::NumericVector depths);
RcppExport SEXP _depthR_depth_outlyingness(SEXP depthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type depths(depthsSEXP);
    rcpp_result_gen = Rcpp::wrap(depth_outlyingness(depths));
    return rcpp_result_gen;
END_RCPP
}
// projection_depth_cpp
Rcpp::NumericVector projection_depth_cpp(Rcpp::NumericMatrix x, Rcpp::NumericMatrix data, double tol, int batch_size, int min_batches, int patience, int seed);
RcppExport SEXP _depthR_projection_depth_cpp(SEXP xSEXP, SEXP dataSEXP, SEXP tolSEXP, SEXP batch_sizeSEXP, SEXP min_batchesSEXP, SEXP patienceSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_batches(min_batchesSEXP);
    Rcpp::traits::input_parameter< int >::type patience(patienceSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(projection_depth_cpp(x, data, tol, batch_size, min_batches, patience, seed));
    return rcpp_result_gen;
END_RCPP
}
// simplicial_depth_cpp
Rcpp::NumericVector simplicial_depth_cpp(Rcpp::NumericMatrix x, Rcpp::NumericMatrix data, double tol, int batch_size, int min_batches, int max_batches, int seed);
RcppExport SEXP _depthR_simplicial_depth_cpp(SEXP xSEXP, SEXP dataSEXP, SEXP tolSEXP, SEXP batch_sizeSEXP, SEXP min_batchesSEXP, SEXP max_batchesSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_batches(min_batchesSEXP);
    Rcpp::traits::input_parameter< int >::type max_batches(max_batchesSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(simplicial_depth_cpp(x, data, tol, batch_size, min_batches, max_batches, seed));
    return rcpp_result_gen;
END_RCPP
}
// spatial_depth_cpp
Rcpp::NumericVector spatial_depth_cpp(Rcpp::NumericMatrix x, Rcpp::NumericMatrix data);
RcppExport SEXP _depthR_spatial_depth_cpp(SEXP xSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(spatial_depth_cpp(x, data));
    return rcpp_result_gen;
END_RCPP
}
// tukey_depth_cpp
Rcpp::NumericVector tukey_depth_cpp(Rcpp::NumericMatrix x, Rcpp::NumericMatrix data, double tol, int batch_size, int min_batches, int patience, int seed);
RcppExport SEXP _depthR_tukey_depth_cpp(SEXP xSEXP, SEXP dataSEXP, SEXP tolSEXP, SEXP batch_sizeSEXP, SEXP min_batchesSEXP, SEXP patienceSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_batches(min_batchesSEXP);
    Rcpp::traits::input_parameter< int >::type patience(patienceSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(tukey_depth_cpp(x, data, tol, batch_size, min_batches, patience, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_depthR_mahalanobis_depth_cpp", (DL_FUNC) &_depthR_mahalanobis_depth_cpp, 4},
    {"_depthR_depth_outlyingness", (DL_FUNC) &_depthR_depth_outlyingness, 1},
    {"_depthR_projection_depth_cpp", (DL_FUNC) &_depthR_projection_depth_cpp, 7},
    {"_depthR_simplicial_depth_cpp", (DL_FUNC) &_depthR_simplicial_depth_cpp, 7},
    {"_depthR_spatial_depth_cpp", (DL_FUNC) &_depthR_spatial_depth_cpp, 2},
    {"_depthR_tukey_depth_cpp", (DL_FUNC) &_depthR_tukey_depth_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_depthR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
